name: "m-connect"
description: "This addon connects to the m-cloud to provide remote access and backup"
version: "1.0.40"
slug: "m_connect"
init: false
url: https://mjos.org
hassio_api: true
privileged:
  - NET_ADMIN
map:
  - config:rw
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  server:
    host: my.VPS.org
    port: 51820
    publickey: inputpublickeyfrommaster
    tunnelip: inputtunnelIP
schema:
  server:
    host: str
    port: port
    publickey: str
    tunnelip: str
