name: "m-connect"
description: "Wireguard client for reverse proxy in cloud setup"
version: "2023.6.9"
slug: "m_connect"
init: false
url: https://github.com/kjetilmjos/m-connect
hassio_api: true
#homeassistant_api: true
hassio_role: "backup"
#auth_api: true
privileged:
  - NET_ADMIN
map:
  - config:rw
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  server:
    host: my.VPS.org
    port: 51820
    publickey: inputpublickeyfrommaster
    tunnelip: inputtunnelIP
    enable_backup: false
    username: username

schema:
  server:
    host: str
    port: port
    publickey: str
    tunnelip: str
    enable_backup: bool
    username: str
